import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clean existing records
  await prisma.reviewLogEntry.deleteMany();
  await prisma.card.deleteMany();
  await prisma.deck.deleteMany();

  const now = new Date();
  const pastDay = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
  const futureDay = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

  // Deck 1: Cellular Biology
  const bioDeck = await prisma.deck.create({
    data: {
      id: 'deck-bio-101',
      title: 'Cell Biology & Energetics',
      sourceType: 'text',
      createdAt: pastDay(10),
    },
  });

  // Cards for Deck 1
  // Card 1: Overdue, high difficulty, low stability (Urgent in both Mastery & Cram)
  const bioCard1 = await prisma.card.create({
    data: {
      id: 'card-bio-01',
      deckId: bioDeck.id,
      type: 'basic',
      front: 'Why does cyanide poisoning halt ATP synthesis in the mitochondria?',
      back: 'Cyanide binds to cytochrome c oxidase (complex IV), stopping the electron transport chain and proton gradient formation.',
      explanation: 'Without proton gradient dissipation through ATP synthase, oxidative phosphorylation halts.',
      due: pastDay(2),
      stability: 1.2,
      difficulty: 8.5,
      reps: 3,
      lapses: 1,
      lastReviewed: pastDay(3),
    },
  });

  // Card 2: Overdue, low difficulty, medium stability (Due in Mastery, lower priority in Cram)
  const bioCard2 = await prisma.card.create({
    data: {
      id: 'card-bio-02',
      deckId: bioDeck.id,
      type: 'cloze',
      front: 'The primary organelle that synthesizes ribosomal RNA is the {{blank}}.',
      back: 'nucleolus',
      explanation: 'The nucleolus resides within the nucleus and coordinates ribosome assembly.',
      due: pastDay(1),
      stability: 5.0,
      difficulty: 2.0,
      reps: 4,
      lapses: 0,
      lastReviewed: pastDay(6),
    },
  });

  // Card 3: Not due yet, high difficulty, low stability (Cram queue prioritizes this! Mastery queue ignores it!)
  const bioCard3 = await prisma.card.create({
    data: {
      id: 'card-bio-03',
      deckId: bioDeck.id,
      type: 'mcq',
      front: 'Which enzyme catalyzes the committed rate-limiting step of glycolysis?',
      back: 'Phosphofructokinase-1 (PFK-1)',
      explanation: 'PFK-1 is allosterically inhibited by ATP and citrate, and activated by AMP and fructose-2,6-bisphosphate.',
      options: JSON.stringify([
        'Phosphofructokinase-1 (PFK-1)',
        'Hexokinase',
        'Pyruvate kinase',
        'Aldolase',
      ]),
      due: futureDay(3), // Not due in mastery!
      stability: 0.8,
      difficulty: 9.0,   // Extremely hard and low stability -> top cram priority!
      reps: 1,
      lapses: 0,
      lastReviewed: pastDay(1),
    },
  });

  // Card 4: Mastered card (stability >= 21 days), due far in future
  const bioCard4 = await prisma.card.create({
    data: {
      id: 'card-bio-04',
      deckId: bioDeck.id,
      type: 'basic',
      front: 'What is the net yield of ATP and NADH per glucose molecule during glycolysis alone?',
      back: '2 net ATP and 2 NADH.',
      explanation: '4 ATP generated by substrate-level phosphorylation minus 2 ATP consumed in the investment phase.',
      due: futureDay(25),
      stability: 28.5, // >= 21 => Mastered!
      difficulty: 3.2,
      reps: 6,
      lapses: 0,
      lastReviewed: pastDay(4),
    },
  });

  // Card 5: Brand new card (due now, reps 0, stability 0)
  const bioCard5 = await prisma.card.create({
    data: {
      id: 'card-bio-05',
      deckId: bioDeck.id,
      type: 'basic',
      front: 'What role does ubiquinone (coenzyme Q) serve in the electron transport chain?',
      back: 'It acts as a lipid-soluble mobile carrier shuttling electrons from Complex I and II to Complex III.',
      explanation: 'Ubiquinone diffuses freely within the hydrophobic core of the inner mitochondrial membrane.',
      due: pastDay(0.1),
      stability: 0,
      difficulty: 5.0,
      reps: 0,
      lapses: 0,
    },
  });

  // Deck 2: Spanish Vocabulary
  const spanishDeck = await prisma.deck.create({
    data: {
      id: 'deck-span-101',
      title: 'Advanced Spanish Medical Vocabulary',
      sourceType: 'pdf',
      createdAt: pastDay(15),
    },
  });

  await prisma.card.create({
    data: {
      id: 'card-span-01',
      deckId: spanishDeck.id,
      type: 'basic',
      front: 'How do you say "shortness of breath" in medical Spanish?',
      back: 'Disnea (o dificultad para respirar)',
      explanation: 'Disnea is the clinical term; patients often say "falta de aire".',
      due: pastDay(1),
      stability: 14.0,
      difficulty: 4.5,
      reps: 5,
      lapses: 1,
      lastReviewed: pastDay(2),
    },
  });

  await prisma.card.create({
    data: {
      id: 'card-span-02',
      deckId: spanishDeck.id,
      type: 'basic',
      front: 'Translate: "The patient presents with acute abdominal guarding."',
      back: 'El paciente presenta defensa abdominal aguda.',
      explanation: 'Defensa abdominal refers to involuntary muscular tension upon palpation.',
      due: futureDay(10),
      stability: 24.0, // Mastered!
      difficulty: 3.0,
      reps: 7,
      lapses: 0,
      lastReviewed: pastDay(5),
    },
  });

  // Add review log entries for stats calculation (accuracy last 7 days)
  await prisma.reviewLogEntry.createMany({
    data: [
      {
        cardId: bioCard1.id,
        deckId: bioDeck.id,
        rating: 'good',
        confidenceBefore: 3,
        reviewedAt: pastDay(3),
        scheduledDays: 2.5,
        elapsedDays: 1.0,
      },
      {
        cardId: bioCard2.id,
        deckId: bioDeck.id,
        rating: 'easy',
        confidenceBefore: 5,
        reviewedAt: pastDay(2),
        scheduledDays: 6.0,
        elapsedDays: 2.0,
      },
      {
        cardId: bioCard3.id,
        deckId: bioDeck.id,
        rating: 'again',
        confidenceBefore: 1,
        reviewedAt: pastDay(1),
        scheduledDays: 0.1,
        elapsedDays: 1.0,
      },
      {
        cardId: bioCard4.id,
        deckId: bioDeck.id,
        rating: 'good',
        confidenceBefore: 4,
        reviewedAt: pastDay(4),
        scheduledDays: 25.0,
        elapsedDays: 12.0,
      },
    ],
  });

  console.log('Seeding complete! Seeded 2 decks and 7 cards with review logs.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
